### ISSUE TITLE
It is compatible with forge 1.16?

### ISSUE THREAD

**Issue by FabioZumbi12** [AlphaBs/CmlLib.Core#6]
Hi and sorry for bother again.

I trying to install forge 1.16.1 like this way:

```// launch forge - its static here but came from my launcher options
var process = launcher.CreateProcess("1.16.1", "32.0.39", launchOption);
```
but i got this issue:
![image](https://user-images.githubusercontent.com/5833818/86297414-a809e080-bbd1-11ea-8d4a-a4df4c58d7cb.png)
_ignore the `config[]`, they are my launcher configs_

When using with 1.12.2 version it downloads and open fine!!
1.16.1 forge version: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.16.1.html

**Comment by AlphaBs** [comment]
2.0.2 is not compatible with 1.16 forge, because 1.6 installer is different from previous version.

This issue will be fixed in 2.0.3

**Comment by FabioZumbi12** [comment]
Cool, thank you!! I am waiting the update ^^

**Comment by AlphaBs** [comment]
I released 3.0.0-alpha3

https://github.com/AlphaBs/CmlLib.Core/releases/tag/v3.0.0-alpha3
or nuget package CmlLib.Core 3.0.0-alpha3

and there are some changes in codes, so see this readme
https://github.com/AlphaBs/CmlLib.Core/blob/master/docs/README-3.0.0.md

**Comment by AlphaBs** [comment]
3.0.0 was released, and it support new forge installer, except 1.7.10 and under versions

if you still could not able to launch 1.16.1, delete game_directory/versions and retry it

**Comment by FabioZumbi12** [comment]
Uhh, thank you!! Ill try when i can. 
The usage still the same?

congratulations for the great work
